name: Build and deploy ASP.Net Core app to Azure Web App - connecthub-auth

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/ConnectHub.Auth/ConnectHub.Auth.csproj

      - name: Build with dotnet
        run: dotnet build ./backend/ConnectHub.Auth/ConnectHub.Auth.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./backend/ConnectHub.Auth/ConnectHub.Auth.csproj -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1AB6EC7E22CA4A3CA38CE4A7B6DC914B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2907937E65C74812B91743937B7371D2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B00AB5C1D2144C829552ECF05D93D8F9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'connecthub-auth'
          slot-name: 'Production'
          package: .